package com.caa.auth.repository;

import com.caa.auth.model.Tenant;
import com.caa.auth.model.TenantLoginConfig;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.test.context.ActiveProfiles;

import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest
@ActiveProfiles("test")
class TenantLoginConfigRepositoryTest {

    @Autowired TenantLoginConfigRepository loginConfigRepository;
    @Autowired TenantRepository tenantRepository;

    private Tenant tenant;

    @BeforeEach
    void setUp() {
        tenant = new Tenant();
        tenant.setCode("pku");
        tenant.setName("北京大学");
        tenant.setType(Tenant.TenantType.SCHOOL);
        tenant.setStatus(Tenant.TenantStatus.ACTIVE);
        tenant.setDefaultLoginType(Tenant.LoginType.PASSWORD);
        tenantRepository.save(tenant);
    }

    private TenantLoginConfig buildConfig(Tenant.LoginType loginType, boolean enabled, boolean isDefault) {
        TenantLoginConfig c = new TenantLoginConfig();
        c.setTenantId(tenant.getId());
        c.setLoginType(loginType);
        c.setEnabled(enabled);
        c.setDefault(isDefault);
        return c;
    }

    @Test
    @DisplayName("findAllByTenantId returns all configs for the tenant")
    void findAllByTenantId_returnsAll() {
        loginConfigRepository.save(buildConfig(Tenant.LoginType.PASSWORD, true, true));
        loginConfigRepository.save(buildConfig(Tenant.LoginType.WECHAT, true, false));

        List<TenantLoginConfig> result = loginConfigRepository.findAllByTenantId(tenant.getId());

        assertThat(result).hasSize(2);
    }

    @Test
    @DisplayName("findAllByTenantId returns empty list when tenant has no configs")
    void findAllByTenantId_empty() {
        assertThat(loginConfigRepository.findAllByTenantId(tenant.getId())).isEmpty();
    }

    @Test
    @DisplayName("findByTenantIdAndLoginType returns matching config")
    void findByTenantIdAndLoginType_found() {
        loginConfigRepository.save(buildConfig(Tenant.LoginType.SSO, true, false));

        Optional<TenantLoginConfig> result =
                loginConfigRepository.findByTenantIdAndLoginType(tenant.getId(), Tenant.LoginType.SSO);

        assertThat(result).isPresent();
        assertThat(result.get().getLoginType()).isEqualTo(Tenant.LoginType.SSO);
    }

    @Test
    @DisplayName("findByTenantIdAndLoginType returns empty when type not configured")
    void findByTenantIdAndLoginType_notFound() {
        Optional<TenantLoginConfig> result =
                loginConfigRepository.findByTenantIdAndLoginType(tenant.getId(), Tenant.LoginType.WECHAT);

        assertThat(result).isEmpty();
    }

    @Test
    @DisplayName("findByTenantIdAndIsDefaultTrue returns the default config")
    void findByTenantIdAndIsDefaultTrue_found() {
        loginConfigRepository.save(buildConfig(Tenant.LoginType.PASSWORD, true, true));
        loginConfigRepository.save(buildConfig(Tenant.LoginType.WECHAT, true, false));

        Optional<TenantLoginConfig> result =
                loginConfigRepository.findByTenantIdAndIsDefaultTrue(tenant.getId());

        assertThat(result).isPresent();
        assertThat(result.get().getLoginType()).isEqualTo(Tenant.LoginType.PASSWORD);
        assertThat(result.get().isDefault()).isTrue();
    }

    @Test
    @DisplayName("findByTenantIdAndIsDefaultTrue returns empty when no default set")
    void findByTenantIdAndIsDefaultTrue_notFound() {
        loginConfigRepository.save(buildConfig(Tenant.LoginType.PASSWORD, true, false));

        Optional<TenantLoginConfig> result =
                loginConfigRepository.findByTenantIdAndIsDefaultTrue(tenant.getId());

        assertThat(result).isEmpty();
    }

    @Test
    @DisplayName("id is auto-generated on persist")
    void idAutoGenerated() {
        TenantLoginConfig saved = loginConfigRepository.save(buildConfig(Tenant.LoginType.PASSWORD, true, true));
        assertThat(saved.getId()).isNotNull().hasSize(36);
    }

    @Test
    @DisplayName("createdAt and updatedAt are set on persist")
    void timestampsSetOnPersist() {
        TenantLoginConfig saved = loginConfigRepository.save(buildConfig(Tenant.LoginType.PASSWORD, true, false));
        assertThat(saved.getCreatedAt()).isNotNull();
        assertThat(saved.getUpdatedAt()).isNotNull();
    }
}
