package com.caa.auth.repository;

import com.caa.auth.model.Tenant;
import com.caa.auth.model.TenantSsoConfig;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.test.context.ActiveProfiles;

import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest
@ActiveProfiles("test")
class TenantSsoConfigRepositoryTest {

    @Autowired TenantSsoConfigRepository ssoConfigRepository;
    @Autowired TenantRepository tenantRepository;

    private Tenant tenant;

    @BeforeEach
    void setUp() {
        tenant = new Tenant();
        tenant.setCode("pku");
        tenant.setName("北京大学");
        tenant.setType(Tenant.TenantType.SCHOOL);
        tenant.setStatus(Tenant.TenantStatus.ACTIVE);
        tenant.setDefaultLoginType(Tenant.LoginType.SSO);
        tenantRepository.save(tenant);
    }

    private TenantSsoConfig buildSsoConfig(boolean enabled) {
        TenantSsoConfig c = new TenantSsoConfig();
        c.setTenantId(tenant.getId());
        c.setIssuerUri("https://idp.example.com");
        c.setClientId("client-abc");
        c.setClientSecret("enc:secret");
        c.setScope("openid profile email");
        c.setEnabled(enabled);
        return c;
    }

    @Test
    @DisplayName("findByTenantId returns config when exists")
    void findByTenantId_found() {
        ssoConfigRepository.save(buildSsoConfig(true));

        Optional<TenantSsoConfig> result = ssoConfigRepository.findByTenantId(tenant.getId());

        assertThat(result).isPresent();
        assertThat(result.get().getIssuerUri()).isEqualTo("https://idp.example.com");
        assertThat(result.get().getClientId()).isEqualTo("client-abc");
    }

    @Test
    @DisplayName("findByTenantId returns empty when no config exists")
    void findByTenantId_notFound() {
        assertThat(ssoConfigRepository.findByTenantId(tenant.getId())).isEmpty();
    }

    @Test
    @DisplayName("findByTenantIdAndEnabled returns config when enabled matches")
    void findByTenantIdAndEnabled_enabledTrue() {
        ssoConfigRepository.save(buildSsoConfig(true));

        Optional<TenantSsoConfig> result =
                ssoConfigRepository.findByTenantIdAndEnabled(tenant.getId(), true);

        assertThat(result).isPresent();
        assertThat(result.get().isEnabled()).isTrue();
    }

    @Test
    @DisplayName("findByTenantIdAndEnabled returns empty when enabled does not match")
    void findByTenantIdAndEnabled_mismatch() {
        ssoConfigRepository.save(buildSsoConfig(false));

        Optional<TenantSsoConfig> result =
                ssoConfigRepository.findByTenantIdAndEnabled(tenant.getId(), true);

        assertThat(result).isEmpty();
    }

    @Test
    @DisplayName("roleMapping stored and retrieved as JSON string")
    void roleMapping_storedAsJsonString() {
        TenantSsoConfig c = buildSsoConfig(true);
        c.setRoleMapping("{\"admin\":\"ROLE_ADMIN\",\"teacher\":\"ROLE_TEACHER\"}");
        ssoConfigRepository.save(c);

        Optional<TenantSsoConfig> result = ssoConfigRepository.findByTenantId(tenant.getId());

        assertThat(result).isPresent();
        assertThat(result.get().getRoleMapping())
                .isEqualTo("{\"admin\":\"ROLE_ADMIN\",\"teacher\":\"ROLE_TEACHER\"}");
    }

    @Test
    @DisplayName("roleClaim is nullable and defaults to null")
    void roleClaim_nullable() {
        TenantSsoConfig saved = ssoConfigRepository.save(buildSsoConfig(true));
        assertThat(saved.getRoleClaim()).isNull();
    }

    @Test
    @DisplayName("id is auto-generated on persist")
    void idAutoGenerated() {
        TenantSsoConfig saved = ssoConfigRepository.save(buildSsoConfig(true));
        assertThat(saved.getId()).isNotNull().hasSize(36);
    }

    @Test
    @DisplayName("createdAt and updatedAt are set on persist")
    void timestampsSetOnPersist() {
        TenantSsoConfig saved = ssoConfigRepository.save(buildSsoConfig(true));
        assertThat(saved.getCreatedAt()).isNotNull();
        assertThat(saved.getUpdatedAt()).isNotNull();
    }

    @Test
    @DisplayName("scope defaults to openid profile email")
    void scopeDefault() {
        TenantSsoConfig c = new TenantSsoConfig();
        c.setTenantId(tenant.getId());
        c.setIssuerUri("https://idp.example.com");
        c.setClientId("client-xyz");
        c.setClientSecret("enc:secret2");
        TenantSsoConfig saved = ssoConfigRepository.save(c);

        assertThat(saved.getScope()).isEqualTo("openid profile email");
    }
}
